version: "3.7"
services:
  web:
    build: .
    restart: unless-stopped
    command: poetry run uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ~/docker_data/raildata_static:/raildata_static
    ports:
      - "8000:8000"
    environment:
      - ALLOW_ORIGINS="https://raildata.ca"